Content Pod Group, Content Panel, Hero
Merkle-XD/sitecore-contentservices-template pull request #16
Opened 2023-05-09 13:45 UTC by cotoole-merkle

2023-05-09 15:59 UTC, cheeto-bandito requested changes
This should be moved into a Draft state until we have group consensus on Base Template standards.

2023-05-10 15:50 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Templates/Basic Content/ContentPodGroup.yml
Can you add an icon to this so it looks nice and pretty, please?

2023-05-10 15:50 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Templates/Basic Content/Hero.yml
Fields look good based on what's currently in the contract but Ryan has some feedback that might affect what fields are on this.

2023-05-10 15:50 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Templates/Basic Content/Hero.yml
Can you add an icon to this so it looks nice and pretty, please?

2023-05-10 15:51 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Templates/Basic Content/ContentPanel.yml
Can you add an icon to this so it looks nice and pretty, please?

2023-05-10 15:52 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Renderings/Basic Content/ContentPanel.yml
I noticed the datasource location and Rendering Contents Resolver are not set. Could you set those and create any associated templates (I looked on Focus and I see things like datasource folders)?

2023-05-10 15:53 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Renderings/Basic Content/Hero.yml
I noticed the datasource location and Rendering Contents Resolver are not set. Could you set those and create any associated templates (I looked on Focus and I see things like datasource folders)?

2023-05-10 15:54 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Renderings/Basic Content/ContentPodGroup.yml
We'll also need a Content Pod rendering that goes inside a content pod group via placeholder. Content Pod will have the datasource template, etc. filled out. Content Pod Group is just a container with a placeholder and no associated datasource template.

2023-05-10 15:57 UTC, JRondeau16 reviewed
There is a separate ticket for the removal of foundation base templates https://degdigital.atlassian.net/browse/GASA-76 so I'm good with this being merged in with existing references to foundation base templates or combining GASA-76 into this. Your choice, @cotoole-merkle

2023-05-10 16:55 UTC, JRondeau16 commented
![image](https://github.com/Merkle-XD/sitecore-contentservices-template/assets/1085463/7c3bc8ed-5cdf-4f59-b30c-1c68daed061c)

Please set a display name to make these content author friendly.

2023-05-11 16:41 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Renderings/Basic Content/ContentPanel.yml
Looks good now.

2023-05-11 17:15 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Renderings/Basic Content/Hero.yml
Looks good.

2023-05-11 17:16 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Templates/Basic Content/ContentPanel.yml
Looks gorgeous!

2023-05-11 17:16 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Templates/Basic Content/Hero.yml
Looks gorgeous!

2023-05-11 17:18 UTC, JRondeau16 commented on scaffolding/merkle.feature.basiccontent/src/Feature/BasicContent/items/Templates/Basic Content/ContentPodGroup.yml
Looks gorgeous!

2023-05-11 17:33 UTC, JRondeau16 requested changes
Add placeholder(s) as needed for content pod group so content pods can go inside of it.

2023-05-11 18:21 UTC, JRondeau16 approved these changes
I haven't seen many things in my life as beautiful as this completed PR. Approved!

2023-05-11 18:21 UTC, JRondeau16 commented
> This should be moved into a Draft state until we have group consensus on Base Template standards.

We're handle the base template removal in a separate ticket. Giving the okay to merge this PR.

2023-05-11 18:25 UTC, merged